# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0044_recover'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(max_length=255, verbose_name='\u6545\u969c\u4fe1\u606f')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u53d1\u751f\u65f6\u95f4')),
                ('status', models.CharField(choices=[('1', '\u5df2\u4fee\u590d'), ('2', '\u672a\u4fee\u590d')], default='1', max_length=255, verbose_name='\u4fee\u590d\u72b6\u6001')),
                ('end_date', models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='\u4fee\u590d\u65f6\u95f4')),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now, help_text='\u9ed8\u8ba4\u503c\u5f53\u524d\u65f6\u95f4,\u53ef\u81ea\u884c\u9009\u62e9', max_length=255, verbose_name='\u62a5\u4fee\u65f6\u95f4')),
                ('memo', models.CharField(blank=True, help_text='\u9009\u586b', max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('hostname', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u540d')),
                ('ip', models.GenericIPAddressField(verbose_name='\u4e3b\u673aIP\u5730\u5740')),
                ('conf', models.CharField(default='\u7f51\u5361bond\u914d\u7f6e:, cpu\u7701\u7535\u786c\u4ef6\u914d\u7f6e:, cpu\u7701\u7535\u8f6f\u4ef6\u914d\u7f6e:, cpu\u8d85\u7ebf\u7a0b:, bios\u7248\u672c:, \u6587\u4ef6\u7cfb\u7edfxfs:, \u865a\u62df\u5316\u8d85\u5206:', max_length=255, verbose_name='\u914d\u7f6e\u9879')),
                ('pebrand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pebrand_model', to='cmdb.BrandModel', verbose_name='\u54c1\u724c/\u578b\u53f7')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhysicalError_error', to='cmdb.PrartType', verbose_name='\u6545\u969c\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '/Meta/\u786c\u4ef6\u6545\u969c',
                'verbose_name_plural': '/Meta/\u786c\u4ef6\u6545\u969c',
            },
        ),
        migrations.AlterField(
            model_name='recover',
            name='end_date',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
    ]
